# Generated by Django 5.0.4 on 2024-05-01 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deportes', '0002_alter_deporte_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='entrenador',
            name='deporte',
        ),
        migrations.AddField(
            model_name='deporte',
            name='entrenador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Deportes.entrenador'),
        ),
        migrations.AlterField(
            model_name='deporte',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='entrenador',
            name='jugador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Deportes.equipo'),
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('jugador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Deportes.equipo')),
            ],
        ),
        migrations.AddField(
            model_name='deporte',
            name='jugador',
            field=models.ManyToManyField(to='Deportes.jugador'),
        ),
        migrations.DeleteModel(
            name='Grupo',
        ),
    ]
