# Generated by Django 5.0.4 on 2024-05-01 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Deportes', '0003_equipo_remove_entrenador_deporte_deporte_entrenador_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrenador',
            old_name='jugador',
            new_name='equipo',
        ),
    ]
