# Generated by Django 5.0.4 on 2024-05-01 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deportes', '0004_rename_jugador_entrenador_equipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entrenador',
            options={'verbose_name_plural': 'Entrenadores'},
        ),
        migrations.AlterModelOptions(
            name='jugador',
            options={'verbose_name_plural': 'jugadores'},
        ),
        migrations.AlterField(
            model_name='deporte',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre del deporte'),
        ),
        migrations.AlterField(
            model_name='entrenador',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre del entrenador'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre del equipo'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='jugador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Deportes.equipo', verbose_name='Equipo'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre del jugador'),
        ),
    ]
