# Generated by Django 5.0.4 on 2024-05-01 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListaCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True, verbose_name='descripción')),
            ],
            options={
                'verbose_name': 'tipos de pinturas',
                'verbose_name_plural': 'tipos de pinturas',
            },
        ),
    ]
