# Generated by Django 5.0.4 on 2024-05-02 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pintura', '0002_lienzos_materiales_tipopintura_delete_listacategoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materiales',
            options={'verbose_name': 'tipos de herramientas', 'verbose_name_plural': 'tipos de herramienta'},
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre pintor')),
                ('lienzo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Pintura.lienzos')),
                ('materiales', models.ManyToManyField(to='Pintura.materiales')),
            ],
        ),
    ]
